// Copyright © 2026 Eric Thai - Thai Ba Hoa. Licensed under PolyForm Noncommercial 1.0.0 — see LICENSE.txt.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  pickVault: () => ipcRenderer.invoke('vault:pick'),
  openVault: (dir) => ipcRenderer.invoke('vault:open', dir),
  reload: () => ipcRenderer.invoke('vault:reload'),
  lastVault: () => ipcRenderer.invoke('vault:last'),
  recent: () => ipcRenderer.invoke('vault:recent'),
  readNote: (rel) => ipcRenderer.invoke('note:read', rel),
  search: (q, limit) => ipcRenderer.invoke('index:search', q, limit),
  testCrashIndexer: () => ipcRenderer.invoke('test:crash-indexer'),
  dvQuery: (q, origin) => ipcRenderer.invoke('index:dv', q, origin),
  snippets: (target, sources) => ipcRenderer.invoke('index:snippets', target, sources),
  graphLayout: (args) => ipcRenderer.invoke('graph:layout', args),
  graphRaster: (args) => ipcRenderer.invoke('graph:raster', args),
  graphPutLayout: (args) => ipcRenderer.invoke('graph:putLayout', args),
  onIndexEvent: (fn) => ipcRenderer.on('index:event', (_e, m) => fn(m)),
  loadNote: (rel) => ipcRenderer.invoke('note:load', rel),
  saveNote: (rel, text, baseMtime, force) => ipcRenderer.invoke('note:save', rel, text, baseMtime, force),
  createNote: (rel, text) => ipcRenderer.invoke('note:create', rel, text),
  exists: (rel) => ipcRenderer.invoke('file:exists', rel),
  fileStat: (rel) => ipcRenderer.invoke('file:stat', rel),
  openWithDefault: (rel) => ipcRenderer.invoke('file:openDefault', rel),
  rename: (from, to) => ipcRenderer.invoke('file:rename', from, to),
  trash: (rel) => ipcRenderer.invoke('file:trash', rel),
  mkdir: (rel) => ipcRenderer.invoke('file:mkdir', rel),
  attach: (dirRel, name, bytes) => ipcRenderer.invoke('file:attach', dirRel, name, bytes),
  flushed: () => ipcRenderer.send('window:flushed'),
  closeWindow: () => ipcRenderer.send('window:close'),
  appInfo: () => ipcRenderer.invoke('app:info'),
  about: () => ipcRenderer.invoke('app:about'),
  doc: (kind) => ipcRenderer.invoke('app:doc', kind),
  licence: (which) => ipcRenderer.invoke('app:licence', which),
  openUserData: () => ipcRenderer.invoke('app:openUserData'),
  mcpInfo: () => ipcRenderer.invoke('app:mcp'),
  copy: (text) => ipcRenderer.invoke('app:copy', text),
  versions: (rel) => ipcRenderer.invoke('note:versions', rel),
  reveal: (rel) => ipcRenderer.invoke('file:reveal', rel),
  openExternal: (url) => ipcRenderer.invoke('shell:external', url),
  getSetting: (k) => ipcRenderer.invoke('settings:get', k),
  setSetting: (k, v) => ipcRenderer.invoke('settings:set', k, v),
  onChanged: (fn) => ipcRenderer.on('vault:changed', (_e, info) => fn(info)),
  onMenu: (fn) => ipcRenderer.on('menu', (_e, cmd) => fn(cmd)),
});
