const ok = (name, cond, extra = '') => log((cond ? 'PASS ' : 'FAIL ') + name, extra);
await until("typeof V !== 'undefined' && current === 'Home.md'", 30000);
ok('pictures listed in the file tree', (await ev("g('tree').querySelectorAll('.row.img').length")) >= 0, await ev("V.images.length + ' images indexed'"));
await ev("(() => { const li = [...document.querySelectorAll('#tree li.dir')].find(l => l.dataset.dir === 'pics'); if (li) toggleDir(li); })()");
ok('tree shows the 3 pictures', (await ev("g('tree').querySelectorAll('.row.img').length")) === 3);
await sleep(500);
await ev("document.querySelector('#note img').click()");
await until("Viewer.isOpen() && /×/.test(g('viewInfo').textContent)", 5000);
ok('click on a note image opens the viewer', true, await ev("g('viewName').textContent + ' · ' + g('viewInfo').textContent + ' · ' + g('viewCount').textContent"));
await shot('v1-viewer-fit');
await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'ArrowRight', code: 'ArrowRight', windowsVirtualKeyCode: 39 });
await send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'ArrowRight', code: 'ArrowRight', windowsVirtualKeyCode: 39 });
await until("g('viewName').textContent === 'logo.svg'", 5000);
ok('→ goes to the next image of the note', true, await ev("g('viewName').textContent + ' · ' + g('viewCount').textContent"));
const b = JSON.parse(await ev("JSON.stringify(g('viewStage').getBoundingClientRect())"));
const z0 = await ev("g('viewZoom').textContent");
await send('Input.dispatchMouseEvent', { type: 'mouseWheel', x: b.x + b.width / 2, y: b.y + b.height / 2, deltaX: 0, deltaY: -400 });
await sleep(200);
ok('wheel zooms', (await ev("g('viewZoom').textContent")) !== z0, z0 + ' → ' + await ev("g('viewZoom').textContent"));
await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 });
await sleep(200);
ok('Esc closes the viewer', !(await ev("Viewer.isOpen()")));
await ev("document.querySelector('#tree .row.img[data-path=\"pics/sunset.png\"]').click()");
await until("Viewer.isOpen() && /×/.test(g('viewInfo').textContent)", 5000);
ok('tree click opens folder browsing', /3$/.test(await ev("g('viewCount').textContent")), await ev("g('viewName').textContent + ' · ' + g('viewInfo').textContent + ' · ' + g('viewCount').textContent"));
await ev("g('view100').click()"); await sleep(200);
ok('100% button', (await ev("g('viewZoom').textContent")) === '100%');
await shot('v2-viewer-100');
await ev("Viewer.close(); openSwitcher(); g('swInput').value = 'suns'; swFilter();");
ok('quick open finds pictures', /sunset\.png/.test(await ev("g('swList').textContent")));
await ev("closeSwitcher(); Prefs.set('showImages', false)");
ok('setting hides pictures from the tree', (await ev("g('tree').querySelectorAll('.row.img').length")) === 0);
await ev("Prefs.set('showImages', true)");
