await until("typeof V !== 'undefined' && V.notes.length > 100000 && !!current", 240000);
const fps = (ms) => `(async () => { let n = 0, worst = 0, last = performance.now(); const t0 = last; await new Promise(res => { const f = (t) => { n++; worst = Math.max(worst, t - last); last = t; if (t - t0 < ${ms}) requestAnimationFrame(f); else res(); }; requestAnimationFrame(f); }); return {fps: +(n / (${ms}/1000)).toFixed(1), worstFrameMs: Math.round(worst)}; })()`;
let t = Date.now();
await ev("toggleGraph('global')");
await until("/links/.test(g('graphInfo').textContent)", 300000);
log('map ready', Date.now() - t, 'ms');
await sleep(800);
const b = JSON.parse(await ev("JSON.stringify(g('graphCanvas').getBoundingClientRect())"));
const cx = b.x + b.width / 2, cy = b.y + b.height / 2;
const pan = async (label) => {
  let go = true;
  const p = (async () => { await send('Input.dispatchMouseEvent', { type: 'mousePressed', x: cx, y: cy, button: 'left', clickCount: 1 }); let i = 0; while (go) { await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: cx + Math.sin(i / 10) * 200, y: cy + Math.cos(i / 13) * 150, button: 'left', buttons: 1 }); i++; await sleep(16); } await send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: cx, y: cy, button: 'left', clickCount: 1 }); })();
  const r = await ev(fps(3000)); go = false; await p; await sleep(400);
  log(label.padEnd(22), 'pan', JSON.stringify(r), '| settled frame', await ev("JSON.stringify(Atlas.frame)"));
};
const wheel = async (n, dy) => { for (let z = 0; z < n; z++) { await send('Input.dispatchMouseEvent', { type: 'mouseWheel', x: cx, y: cy, deltaX: 0, deltaY: dy }); await sleep(60); } await sleep(400); };
log('initial frame', await ev("JSON.stringify(Atlas.frame)"));
await pan('focus zoom');
await ev("Atlas.fit()"); await sleep(400);
await pan('overview');
await wheel(4, -300); await pan('mid zoom');
await wheel(6, -300); await pan('close zoom');
await shot('70-map-close');
await ev("Atlas.fit()"); await sleep(400);
await shot('71-map-overview');
await ev("setTheme('dark')"); await sleep(600);
await shot('72-map-dark');
await ev("setTheme('light')");
await ev("(() => { g('graphFind').value = 'AMM 29-11'; g('graphFind').oninput(); })()");
await sleep(800);
log('find', await ev("g('graphInfo').textContent"), await ev("JSON.stringify(Atlas.frame)"));
await shot('73-map-find');
t = Date.now();
await ev("Graph.show('local', 'AMM/05/AMM 05-00-00-00.md')");
log('local', Date.now() - t, 'ms', await ev("g('graphInfo').textContent"));
await sleep(400); await shot('74-map-local-small');
await ev("Graph.show('local', 'CAGE/CAGE FAPE3.md')"); await sleep(400);
await shot('75-map-local-hub');
log('heap MB', await ev("Math.round(performance.memory.usedJSHeapSize/2**20)"));
